### ISSUE TITLE
论文中MT-DNN Layers 说明错误

### ISSUE THREAD

**Issue by luoqishuai** [DandyQi/CentraBert-OpenSource#6]
Table 2
MT-DNN的Layers应该为`12*8`.
因为MT-DNN是使用多任务学习,训练一个模型.然后再在各个任务上进行fine-turning,所以应该为`12*8`.(参考https://github.com/microsoft/MT-DNN#did-you-fine-tune-single-task-for-your-glue-leaderboard-submission)
不知道我的理解是否正确

**Comment by DandyQi** [comment]
你好，

我们在实验中，使用多任务训练后，的确在各任务上进行了fine-tuning，但此时我们将transformer部分固定，仅训练每个任务的output-layer。因此在实验结果中，我们认为MT-DNN方案的transformer开销为 12*1。

上述微调过程可能与MT-DNN所述方案略有差别，我们将考虑更新在实验中。

多谢。
